# Generated by Django 4.0.6 on 2022-08-02 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_provider_debt'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='provider',
        ),
        migrations.AlterField(
            model_name='providerproduct',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_products', to='providers.provider'),
        ),
    ]
