# Generated by Django 4.0.6 on 2022-08-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_provider_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProviderProduct',
        ),
    ]
