# Generated by Django 4.0.6 on 2022-08-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_remove_provider_product'),
        ('products', '0003_delete_providerproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='providers',
            field=models.ManyToManyField(related_name='products', to='providers.provider'),
        ),
    ]
