# Generated by Django 4.0.6 on 2022-08-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_providerproduct'),
        ('providers', '0002_alter_provider_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='product',
            field=models.ManyToManyField(related_name='providers', to='products.product'),
        ),
    ]
