# Generated by Django 4.0.6 on 2022-08-02 12:36

from django.db import migrations, models
import employees.validations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, validators=[employees.validations.validate_birthday]),
        ),
    ]
